name: 'Send Tweet V2 Action'
description: 'Post a tweet using V2 API to Twitter during a GitHub Actions workflow.'
author: 'Jonathan Gao'
inputs:
  message:
    description: The status ("tweet") to post to twitter.
    required: true
  bearer-token:
    description: Bearer Token
    required: true
  consumer-key:
    description: >
      Consumer API key, available in the "Keys and tokens"
    default: ""
  consumer-secret:
    description: >
      Consumer API secret key, available in the "Keys and tokens"
    default: ""
  access-token:
    description: >
      Application access token, available in the "Keys and tokens"
    default: ""
  access-token-secret:
    description: >
      Application access token secret, available in the "Keys and tokens"
    default: ""
runs:
  using: "composite"
  steps:
    - name: Send Tweet Message
      run: bash -c "exe/send-tweet-v2"
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
        BEARER_TOKEN: ${{ inputs.bearer-token }}
        CONSUMER_KEY: ${{ inputs.consumer-key }}
        CONSUMER_SECRET: ${{ inputs.consumer-secret }}
        ACCESS_TOKEN: ${{ inputs.access-token }}
        ACCESS_SECRET: ${{ inputs.access-token-secret }}
branding:
  icon: edit
  color: blue
